export enum SmithNamesEnum {
  ASMOI = `Asmoi`,
  BEHE = `Behe`,
  BOB = `Bob`,
  CHARLOTTE = `Charlotte`,
  CHARLY = `Charly`,
  DANTAL = `Dantal`,
  DIPLORIUS = `Diplorius`,
  DONINIC = `Dominic`,
  LEIA = `Leia`,
  LEVY = `Levy`,
  MARCO = `Marco`,
  NAZOKEE = `Nazokee`,
  NIGUEL = `Niguel`,
  SOHPIA = `Sophia`,
  SYTRE = `Sytre`,
  SYTROS = `Sytros`,
  SYTRY = `Sytry`,
}
